development: &default
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_TOKEN_BASE'] %>
  shiftplanning_key: <%= ENV['SHIFTPLANNING_KEY'] %>
  shiftplanning_login: <%= ENV['SHIFTPLANNING_LOGIN'] %> 
  shiftplanning_password: <%= ENV['SHIFTPLANNING_PASSWORD'] %> 
  tocat_manager: <%= ENV['TOCAT_OWNER'] %>
  tempo_api_key: <%= ENV['TEMPO_API_KEY'] %>

test:
  <<: *default
production:
  <<: *default
